config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :suppliers

  resources :shipping_addresses

  resources :components

  resources :customers

  resources :order_items

  resources :orders

  resources :stocks

  resources :stock_types

  resources :units

  resources :ingredients

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/component.rb
class Component < ActiveRecord::Base
  belongs_to :stock
  has_one :stock
  has_one :unit
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :orders
  has_many :shipping_addresses
  validates_formatting_of :email, using: :email
  validates_formatting_of :phone, using: :us_phone
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :stock_type
  has_one :stock_type
  has_one :unit
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  has_one :shipping_address
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :stock_type
  has_one :stock
  has_one :unit
end

app/models/shipping_address.rb
class ShippingAddress < ActiveRecord::Base
  belongs_to :customer
  belongs_to :order
  validates_formatting_of :zip, using: :us_zip
  validates_formatting_of :email, using: :email
  validates_formatting_of :phone, using: :us_phone
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :supplier
  belongs_to :stock_type
  belongs_to :component
  belongs_to :order_item
  has_many :components
  has_one :unit
end

app/models/stock_type.rb
class StockType < ActiveRecord::Base
  belongs_to :ingredient
  has_many :order_items
  has_many :stocks
  has_many :ingredients
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  has_many :stocks
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  belongs_to :unit
  belongs_to :component
  belongs_to :ingredient
  belongs_to :stock
  belongs_to :order_item
  has_one :unit
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :unit_id, :conversion, :component_id, :ingredient_id, :stock_id, :order_item_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/components_helper.rb
module ComponentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= simple_form_for(@unit) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :unit %>
    <%= f.input :conversion %>
    <%= f.association :component %>
    <%= f.association :ingredient %>
    <%= f.association :stock %>
    <%= f.association :order_item %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<h1>Listing units</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Unit</th>
      <th>Conversion</th>
      <th>Component</th>
      <th>Ingredient</th>
      <th>Stock</th>
      <th>Order item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.name %></td>
        <td><%= unit.unit %></td>
        <td><%= unit.conversion %></td>
        <td><%= unit.component %></td>
        <td><%= unit.ingredient %></td>
        <td><%= unit.stock %></td>
        <td><%= unit.order_item %></td>
        <td><%= link_to 'Show', unit %></td>
        <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
        <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unit', new_unit_path %>

app/views/units/new.html.erb
<h1>New unit</h1>

<%= render 'form' %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @unit.name %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @unit.unit %>
</p>

<p>
  <strong>Conversion:</strong>
  <%= @unit.conversion %>
</p>

<p>
  <strong>Component:</strong>
  <%= @unit.component %>
</p>

<p>
  <strong>Ingredient:</strong>
  <%= @unit.ingredient %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @unit.stock %>
</p>

<p>
  <strong>Order item:</strong>
  <%= @unit.order_item %>
</p>

<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>